/** Web attribute id -> our (Spanish) attribute name. */
export const ATTRIBUTE_ID_TO_NAME: Record<string, string> = {
  acceleration: "Aceleracion",
  sprint_speed: "Sprint",
  att_position: "Posicionamiento",
  finishing: "Definicion",
  shot_power: "Potencia Tiro",
  long_shots: "Tiros Lejanos",
  volleys: "Voleas",
  penalties: "Penales",
  vision: "Vision",
  crossing: "Centros",
  fk_accuracy: "Precision TL",
  short_passing: "Pase Corto",
  long_passing: "Pase Largo",
  curve: "Efecto",
  agility: "Agilidad",
  balance: "Balance",
  reactions: "Reacciones",
  ball_control: "Control Balon",
  dribbling: "Regates",
  composure: "Compostura",
  interceptions: "Intercepciones",
  heading_acc: "Precision Cabeza",
  def_aware: "Percepcion Defensiva",
  standing_tackle: "Robos",
  sliding_tackle: "Barridas",
  jumping: "Salto",
  stamina: "Resistencia",
  strength: "Fuerza",
  aggression: "Agresividad",
  gk_diving: "GK_Estirada",
  gk_handling: "GK_Paradas",
  gk_kicking: "GK_Saque",
  gk_reflexes: "GK_Reflejos",
  gk_positioning: "GK_Colocacion",
};

export const attributeLabel = (id: string): string =>
  ATTRIBUTE_ID_TO_NAME[id] ?? id;
