// Transpiles the official data sources in raw-data/ into typed TypeScript
// modules under src/data/. No values are invented here: every number is read
// verbatim from raw-data/ and cast with Number(). Run with: npm run generate:data
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const RAW = resolve(ROOT, "raw-data");
const OUT = resolve(ROOT, "src", "data");

mkdirSync(OUT, { recursive: true });

/** Minimal RFC-4180-ish CSV parser (handles quotes, commas and CRLF). */
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let inQuotes = false;

  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inQuotes) {
      if (ch === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        field += ch;
      }
    } else if (ch === '"') {
      inQuotes = true;
    } else if (ch === ",") {
      row.push(field);
      field = "";
    } else if (ch === "\n") {
      row.push(field);
      rows.push(row);
      row = [];
      field = "";
    } else if (ch !== "\r") {
      field += ch;
    }
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }

  const [header, ...body] = rows.filter((r) => r.some((c) => c.trim() !== ""));
  return body.map((r) => {
    const obj = {};
    header.forEach((key, idx) => {
      obj[key.trim()] = (r[idx] ?? "").trim();
    });
    return obj;
  });
}

/** Strict numeric cast: every stored numeric value ends up as a `number`. */
const num = (v) => {
  const n = Number(v);
  if (!Number.isFinite(n)) throw new Error(`Valor numérico inválido: "${v}"`);
  return n;
};

const RAW_FILES = readdirSync(RAW);

/** Resolve a logical name to an actual file (supports .csv and .txt). */
function sourceFile(baseName) {
  const match = RAW_FILES.find((f) =>
    new RegExp(`^${baseName}\\.(csv|txt)$`, "i").test(f),
  );
  if (!match) throw new Error(`No se encontró raw-data/${baseName}.{csv,txt}`);
  return readFileSync(resolve(RAW, match), "utf8");
}

const banner = `// AUTO-GENERATED by scripts/generate-data.mjs from raw-data/. Do not edit by hand.`;

// --- 1. Archetypes -------------------------------------------------------
const archetypes = parseCsv(sourceFile("archetypes")).map((r) => ({
  id: num(r.id),
  name: r.name,
  role: r.role,
  primary_position: r.primary_position,
  signature_playstyle_plus: r.signature_playstyle_plus,
  specializations: r.specializations
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean),
  inspired_by: r.inspired_by,
  min_height: num(r.min_height),
  max_height: num(r.max_height),
  default_height: num(r.default_height),
  min_weight: num(r.min_weight),
  max_weight: num(r.max_weight),
  default_weight: num(r.default_weight),
  base_ap: num(r.base_ap),
}));

// --- 2. Archetype attributes --------------------------------------------
const attributeRows = parseCsv(sourceFile("archetype_attributes")).map((r) => ({
  archetype: r.archetype,
  category: r.category,
  attribute: r.attribute,
  base_stat: num(r.base_stat),
  cap_stat: num(r.cap_stat),
  cost_tier: r.cost_tier,
}));

const attributesByArchetype = {};
for (const row of attributeRows) {
  (attributesByArchetype[row.archetype] ??= []).push(row);
}

// --- 3. Cost tiers -------------------------------------------------------
const TIGHT_KEYS = {
  Cheapest: "tier_cheapest",
  Cheap: "tier_cheap",
  Expensive: "tier_expensive",
  "Most Expensive": "tier_most_expensive",
};

const costTiers = parseCsv(sourceFile("cost_tiers")).map((r) => ({
  min: num(r.min_stat),
  max: num(r.max_stat),
  rates: {
    Cheapest: num(r[TIGHT_KEYS.Cheapest]),
    Cheap: num(r[TIGHT_KEYS.Cheap]),
    Expensive: num(r[TIGHT_KEYS.Expensive]),
    "Most Expensive": num(r[TIGHT_KEYS["Most Expensive"]]),
  },
}));

// --- 4. Archetype masteries (fixed max-level bonuses) --------------------
const isNumeric = (v) => v !== undefined && v !== "" && Number.isFinite(Number(v));

const masteryRows = parseCsv(sourceFile("archetype_masteries")).map((r) => {
  let stat_1 = r.stat_1;
  let bonus_1 = r.bonus_1;
  let stat_2 = r.stat_2;
  let bonus_2 = r.bonus_2;

  // Defensive: some source rows may omit a bonus (e.g. "Recycler,Percepcion
  // Defensiva,Pase Corto,2"). Re-align the ragged row without inventing values:
  // the missing bonus becomes 0 and the remaining fields shift into place.
  if (!isNumeric(bonus_1) && isNumeric(stat_2)) {
    bonus_2 = stat_2;
    stat_2 = bonus_1;
    bonus_1 = "0";
    console.warn(
      `Masteries: fila irregular para "${r.archetype}" (falta bonus_1) — se asigna bonus_1 = 0.`,
    );
  }

  return {
    archetype: r.archetype,
    stat_1,
    bonus_1: num(bonus_1),
    stat_2,
    bonus_2: num(bonus_2),
  };
});

// --- 5. Archetype stars (skill moves / weak foot) ------------------------
const starRows = parseCsv(sourceFile("archetype_stars")).map((r) => ({
  archetype: r.archetype,
  base_skills: num(r.base_skills),
  max_skills: num(r.max_skills),
  cost_skills_3: num(r.cost_skills_3),
  cost_skills_4: num(r.cost_skills_4),
  cost_skills_5: num(r.cost_skills_5),
  base_weak_foot: num(r.base_weak_foot),
  max_weak_foot: num(r.max_weak_foot),
  cost_wf_3: num(r.cost_wf_3),
  cost_wf_4: num(r.cost_wf_4),
  cost_wf_5: num(r.cost_wf_5),
}));

// --- Write archetypes + attributes + cost tiers + masteries --------------
const archetypesFile = `${banner}
import type { Archetype } from "@/types";

export const ARCHETYPES: Archetype[] = ${JSON.stringify(archetypes, null, 2)};

export const DEFAULT_ARCHETYPE = ARCHETYPES[0].name;

export const ARCHETYPE_BY_NAME: Record<string, Archetype> = Object.fromEntries(
  ARCHETYPES.map((a) => [a.name, a]),
);

export function getArchetype(name: string): Archetype | undefined {
  return ARCHETYPE_BY_NAME[name];
}
`;

const attrsFile = `${banner}
import type { ArchetypeAttribute } from "@/types";

export const ATTRIBUTES_BY_ARCHETYPE: Record<string, ArchetypeAttribute[]> = ${
  JSON.stringify(attributesByArchetype, null, 2)
};

export function getArchetypeAttributes(name: string): ArchetypeAttribute[] {
  return ATTRIBUTES_BY_ARCHETYPE[name] ?? [];
}

/** All attribute names referenced by any archetype (stable order). */
export const ALL_ATTRIBUTES: string[] = Array.from(
  new Set(Object.values(ATTRIBUTES_BY_ARCHETYPE).flat().map((a) => a.attribute)),
);

export const CATEGORIES_BY_ARCHETYPE: Record<string, string[]> = Object.fromEntries(
  Object.entries(ATTRIBUTES_BY_ARCHETYPE).map(([name, attrs]) => [
    name,
    Array.from(new Set(attrs.map((a) => a.category))),
  ]),
);
`;

const tiersFile = `${banner}
import type { CostTierRange } from "@/types";

export const COST_TIERS_TABLE: CostTierRange[] = ${JSON.stringify(costTiers, null, 2)};
`;

const masteriesFile = `${banner}
import type { ArchetypeMastery } from "@/types";

export const ARCHETYPE_MASTERIES: ArchetypeMastery[] = ${JSON.stringify(
  masteryRows,
  null,
  2,
)};

export const MASTERY_BY_ARCHETYPE: Record<string, ArchetypeMastery> =
  Object.fromEntries(ARCHETYPE_MASTERIES.map((m) => [m.archetype, m]));

export function getMastery(name: string): ArchetypeMastery | undefined {
  return MASTERY_BY_ARCHETYPE[name];
}
`;

const starsFile = `${banner}
import type { ArchetypeStars } from "@/types";

export const ARCHETYPE_STARS: ArchetypeStars[] = ${JSON.stringify(
  starRows,
  null,
  2,
)};

export const STARS_BY_ARCHETYPE: Record<string, ArchetypeStars> =
  Object.fromEntries(ARCHETYPE_STARS.map((s) => [s.archetype, s]));

export function getStars(name: string): ArchetypeStars | undefined {
  return STARS_BY_ARCHETYPE[name];
}
`;

writeFileSync(resolve(OUT, "archetypes.ts"), archetypesFile);
writeFileSync(resolve(OUT, "archetypeAttributes.ts"), attrsFile);
writeFileSync(resolve(OUT, "costTiers.ts"), tiersFile);
writeFileSync(resolve(OUT, "archetypeMasteries.ts"), masteriesFile);
writeFileSync(resolve(OUT, "archetypeStars.ts"), starsFile);

// Physical modifiers (height/weight) are intentionally NOT generated: the app
// no longer applies physical modifiers. raw-data/physical_modifiers.* is left
// untouched for reference only.

console.log(
  `Generated: ${archetypes.length} archetypes, ${attributeRows.length} attributes, ${costTiers.length} cost tiers, ${masteryRows.length} masteries, ${starRows.length} star rows.`,
);
