// AUTO-GENERATED by scripts/generate-data.mjs from raw-data/. Do not edit by hand.
import type { ArchetypeAttribute, CategoryName } from "@/types";

export const ATTRIBUTES_BY_ARCHETYPE: Record<string, ArchetypeAttribute[]> = {
  "Finisher": [
    {
      "category": "Pace",
      "attribute": "Aceleracion",
      "baseStat": 70,
      "capStat": 94,
      "costTier": "Cheapest"
    },
    {
      "category": "Pace",
      "attribute": "Sprint",
      "baseStat": 75,
      "capStat": 96,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Posicionamiento",
      "baseStat": 80,
      "capStat": 95,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Definicion",
      "baseStat": 75,
      "capStat": 99,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Potencia de Tiro",
      "baseStat": 75,
      "capStat": 94,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Tiros Lejanos",
      "baseStat": 60,
      "capStat": 88,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Voleas",
      "baseStat": 75,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Penales",
      "baseStat": 75,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Vision",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Cheapest"
    },
    {
      "category": "Passing",
      "attribute": "Centros",
      "baseStat": 55,
      "capStat": 78,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Pase Corto",
      "baseStat": 70,
      "capStat": 88,
      "costTier": "Most Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Pase Largo",
      "baseStat": 50,
      "capStat": 75,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Efecto",
      "baseStat": 70,
      "capStat": 86,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Agilidad",
      "baseStat": 72,
      "capStat": 96,
      "costTier": "Cheapest"
    },
    {
      "category": "Dribbling",
      "attribute": "Balance",
      "baseStat": 75,
      "capStat": 90,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Reacciones",
      "baseStat": 75,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Control Balon",
      "baseStat": 75,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Regates",
      "baseStat": 70,
      "capStat": 95,
      "costTier": "Cheapest"
    },
    {
      "category": "Dribbling",
      "attribute": "Compostura",
      "baseStat": 75,
      "capStat": 94,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Intercepciones",
      "baseStat": 60,
      "capStat": 85,
      "costTier": "Most Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "baseStat": 75,
      "capStat": 94,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "baseStat": 55,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Robos",
      "baseStat": 50,
      "capStat": 75,
      "costTier": "Most Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Barridas",
      "baseStat": 40,
      "capStat": 75,
      "costTier": "Expensive"
    },
    {
      "category": "Physical",
      "attribute": "Salto",
      "baseStat": 65,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Resistencia",
      "baseStat": 65,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Fuerza",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Expensive"
    },
    {
      "category": "Physical",
      "attribute": "Agresividad",
      "baseStat": 65,
      "capStat": 90,
      "costTier": "Cheap"
    }
  ],
  "Magician": [
    {
      "category": "Pace",
      "attribute": "Aceleracion",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Most Expensive"
    },
    {
      "category": "Pace",
      "attribute": "Sprint",
      "baseStat": 70,
      "capStat": 92,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Posicionamiento",
      "baseStat": 80,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Definicion",
      "baseStat": 75,
      "capStat": 90,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Potencia de Tiro",
      "baseStat": 70,
      "capStat": 88,
      "costTier": "Cheapest"
    },
    {
      "category": "Shooting",
      "attribute": "Tiros Lejanos",
      "baseStat": 65,
      "capStat": 90,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Voleas",
      "baseStat": 72,
      "capStat": 92,
      "costTier": "Cheapest"
    },
    {
      "category": "Shooting",
      "attribute": "Penales",
      "baseStat": 75,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Vision",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Centros",
      "baseStat": 65,
      "capStat": 90,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Pase Corto",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Most Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Pase Largo",
      "baseStat": 50,
      "capStat": 88,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Efecto",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Agilidad",
      "baseStat": 72,
      "capStat": 99,
      "costTier": "Most Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Balance",
      "baseStat": 75,
      "capStat": 96,
      "costTier": "Cheapest"
    },
    {
      "category": "Dribbling",
      "attribute": "Reacciones",
      "baseStat": 75,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Control Balon",
      "baseStat": 75,
      "capStat": 96,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Regates",
      "baseStat": 75,
      "capStat": 98,
      "costTier": "Most Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Compostura",
      "baseStat": 72,
      "capStat": 94,
      "costTier": "Cheapest"
    },
    {
      "category": "Defending",
      "attribute": "Intercepciones",
      "baseStat": 50,
      "capStat": 82,
      "costTier": "Most Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "baseStat": 45,
      "capStat": 82,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Robos",
      "baseStat": 40,
      "capStat": 75,
      "costTier": "Most Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Barridas",
      "baseStat": 40,
      "capStat": 75,
      "costTier": "Expensive"
    },
    {
      "category": "Physical",
      "attribute": "Salto",
      "baseStat": 60,
      "capStat": 85,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Resistencia",
      "baseStat": 65,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Fuerza",
      "baseStat": 65,
      "capStat": 88,
      "costTier": "Expensive"
    },
    {
      "category": "Physical",
      "attribute": "Agresividad",
      "baseStat": 55,
      "capStat": 88,
      "costTier": "Cheap"
    }
  ],
  "Spark": [
    {
      "category": "Pace",
      "attribute": "Aceleracion",
      "baseStat": 75,
      "capStat": 99,
      "costTier": "Most Expensive"
    },
    {
      "category": "Pace",
      "attribute": "Sprint",
      "baseStat": 75,
      "capStat": 99,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Posicionamiento",
      "baseStat": 80,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Definicion",
      "baseStat": 65,
      "capStat": 88,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Potencia de Tiro",
      "baseStat": 65,
      "capStat": 88,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Tiros Lejanos",
      "baseStat": 65,
      "capStat": 92,
      "costTier": "Cheapest"
    },
    {
      "category": "Shooting",
      "attribute": "Voleas",
      "baseStat": 72,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Penales",
      "baseStat": 75,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Vision",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheapest"
    },
    {
      "category": "Passing",
      "attribute": "Centros",
      "baseStat": 75,
      "capStat": 94,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Pase Corto",
      "baseStat": 75,
      "capStat": 92,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Pase Largo",
      "baseStat": 65,
      "capStat": 88,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Efecto",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheapest"
    },
    {
      "category": "Dribbling",
      "attribute": "Agilidad",
      "baseStat": 75,
      "capStat": 99,
      "costTier": "Most Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Balance",
      "baseStat": 75,
      "capStat": 94,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Reacciones",
      "baseStat": 75,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Control Balon",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Regates",
      "baseStat": 75,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Dribbling",
      "attribute": "Compostura",
      "baseStat": 72,
      "capStat": 90,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Intercepciones",
      "baseStat": 55,
      "capStat": 85,
      "costTier": "Most Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "baseStat": 50,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "baseStat": 50,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Robos",
      "baseStat": 55,
      "capStat": 80,
      "costTier": "Most Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Barridas",
      "baseStat": 45,
      "capStat": 75,
      "costTier": "Expensive"
    },
    {
      "category": "Physical",
      "attribute": "Salto",
      "baseStat": 55,
      "capStat": 85,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Resistencia",
      "baseStat": 65,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Fuerza",
      "baseStat": 65,
      "capStat": 86,
      "costTier": "Expensive"
    },
    {
      "category": "Physical",
      "attribute": "Agresividad",
      "baseStat": 50,
      "capStat": 88,
      "costTier": "Cheap"
    }
  ],
  "Disruptor": [
    {
      "category": "Pace",
      "attribute": "Aceleracion",
      "baseStat": 75,
      "capStat": 92,
      "costTier": "Expensive"
    },
    {
      "category": "Pace",
      "attribute": "Sprint",
      "baseStat": 70,
      "capStat": 92,
      "costTier": "Cheapest"
    },
    {
      "category": "Shooting",
      "attribute": "Posicionamiento",
      "baseStat": 70,
      "capStat": 88,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Definicion",
      "baseStat": 50,
      "capStat": 80,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Potencia de Tiro",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Tiros Lejanos",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Voleas",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Penales",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Vision",
      "baseStat": 65,
      "capStat": 88,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Centros",
      "baseStat": 65,
      "capStat": 90,
      "costTier": "Cheapest"
    },
    {
      "category": "Passing",
      "attribute": "Pase Corto",
      "baseStat": 75,
      "capStat": 96,
      "costTier": "Most Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Pase Largo",
      "baseStat": 70,
      "capStat": 92,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Efecto",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Agilidad",
      "baseStat": 68,
      "capStat": 88,
      "costTier": "Most Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Balance",
      "baseStat": 75,
      "capStat": 90,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Reacciones",
      "baseStat": 70,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Control Balon",
      "baseStat": 65,
      "capStat": 90,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Regates",
      "baseStat": 65,
      "capStat": 88,
      "costTier": "Most Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Compostura",
      "baseStat": 70,
      "capStat": 92,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Intercepciones",
      "baseStat": 75,
      "capStat": 98,
      "costTier": "Most Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "baseStat": 65,
      "capStat": 92,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "baseStat": 70,
      "capStat": 96,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Robos",
      "baseStat": 70,
      "capStat": 98,
      "costTier": "Most Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Barridas",
      "baseStat": 75,
      "capStat": 98,
      "costTier": "Cheapest"
    },
    {
      "category": "Physical",
      "attribute": "Salto",
      "baseStat": 65,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Resistencia",
      "baseStat": 75,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Physical",
      "attribute": "Fuerza",
      "baseStat": 75,
      "capStat": 98,
      "costTier": "Expensive"
    },
    {
      "category": "Physical",
      "attribute": "Agresividad",
      "baseStat": 70,
      "capStat": 99,
      "costTier": "Expensive"
    }
  ],
  "Maestro": [
    {
      "category": "Pace",
      "attribute": "Aceleracion",
      "baseStat": 70,
      "capStat": 88,
      "costTier": "Most Expensive"
    },
    {
      "category": "Pace",
      "attribute": "Sprint",
      "baseStat": 65,
      "capStat": 88,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Posicionamiento",
      "baseStat": 80,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Definicion",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Potencia de Tiro",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Tiros Lejanos",
      "baseStat": 70,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Voleas",
      "baseStat": 65,
      "capStat": 88,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Penales",
      "baseStat": 70,
      "capStat": 88,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Vision",
      "baseStat": 75,
      "capStat": 98,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Centros",
      "baseStat": 75,
      "capStat": 92,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Pase Corto",
      "baseStat": 75,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Passing",
      "attribute": "Pase Largo",
      "baseStat": 75,
      "capStat": 98,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Efecto",
      "baseStat": 70,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Agilidad",
      "baseStat": 75,
      "capStat": 92,
      "costTier": "Most Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Balance",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Reacciones",
      "baseStat": 65,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Control Balon",
      "baseStat": 75,
      "capStat": 98,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Regates",
      "baseStat": 65,
      "capStat": 92,
      "costTier": "Most Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Compostura",
      "baseStat": 75,
      "capStat": 96,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Intercepciones",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheapest"
    },
    {
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "baseStat": 50,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "baseStat": 65,
      "capStat": 94,
      "costTier": "Cheapest"
    },
    {
      "category": "Defending",
      "attribute": "Robos",
      "baseStat": 72,
      "capStat": 92,
      "costTier": "Most Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Barridas",
      "baseStat": 50,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Physical",
      "attribute": "Salto",
      "baseStat": 60,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Resistencia",
      "baseStat": 65,
      "capStat": 96,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Fuerza",
      "baseStat": 65,
      "capStat": 92,
      "costTier": "Cheapest"
    },
    {
      "category": "Physical",
      "attribute": "Agresividad",
      "baseStat": 65,
      "capStat": 92,
      "costTier": "Cheap"
    }
  ],
  "Boss": [
    {
      "category": "Pace",
      "attribute": "Aceleracion",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Pace",
      "attribute": "Sprint",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Posicionamiento",
      "baseStat": 40,
      "capStat": 65,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Definicion",
      "baseStat": 35,
      "capStat": 60,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Potencia de Tiro",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Tiros Lejanos",
      "baseStat": 45,
      "capStat": 65,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Voleas",
      "baseStat": 40,
      "capStat": 65,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Penales",
      "baseStat": 50,
      "capStat": 70,
      "costTier": "Most Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Vision",
      "baseStat": 55,
      "capStat": 75,
      "costTier": "Most Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Centros",
      "baseStat": 50,
      "capStat": 75,
      "costTier": "Most Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Pase Corto",
      "baseStat": 70,
      "capStat": 88,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Pase Largo",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Efecto",
      "baseStat": 50,
      "capStat": 70,
      "costTier": "Most Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Agilidad",
      "baseStat": 55,
      "capStat": 80,
      "costTier": "Most Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Balance",
      "baseStat": 60,
      "capStat": 82,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Reacciones",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Control Balon",
      "baseStat": 65,
      "capStat": 88,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Regates",
      "baseStat": 55,
      "capStat": 80,
      "costTier": "Most Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Compostura",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheap"
    },
    {
      "category": "Defending",
      "attribute": "Intercepciones",
      "baseStat": 75,
      "capStat": 96,
      "costTier": "Cheap"
    },
    {
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "baseStat": 80,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "baseStat": 75,
      "capStat": 98,
      "costTier": "Cheap"
    },
    {
      "category": "Defending",
      "attribute": "Robos",
      "baseStat": 75,
      "capStat": 98,
      "costTier": "Cheap"
    },
    {
      "category": "Defending",
      "attribute": "Barridas",
      "baseStat": 75,
      "capStat": 96,
      "costTier": "Cheapest"
    },
    {
      "category": "Physical",
      "attribute": "Salto",
      "baseStat": 75,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Physical",
      "attribute": "Resistencia",
      "baseStat": 70,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Fuerza",
      "baseStat": 80,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Physical",
      "attribute": "Agresividad",
      "baseStat": 75,
      "capStat": 99,
      "costTier": "Cheapest"
    }
  ],
  "Target": [
    {
      "category": "Pace",
      "attribute": "Aceleracion",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Most Expensive"
    },
    {
      "category": "Pace",
      "attribute": "Sprint",
      "baseStat": 65,
      "capStat": 88,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Posicionamiento",
      "baseStat": 78,
      "capStat": 95,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Definicion",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Potencia de Tiro",
      "baseStat": 80,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Shooting",
      "attribute": "Tiros Lejanos",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Voleas",
      "baseStat": 75,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Penales",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Vision",
      "baseStat": 60,
      "capStat": 82,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Centros",
      "baseStat": 50,
      "capStat": 72,
      "costTier": "Most Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Pase Corto",
      "baseStat": 70,
      "capStat": 88,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Pase Largo",
      "baseStat": 55,
      "capStat": 75,
      "costTier": "Most Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Efecto",
      "baseStat": 55,
      "capStat": 75,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Agilidad",
      "baseStat": 55,
      "capStat": 78,
      "costTier": "Most Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Balance",
      "baseStat": 60,
      "capStat": 82,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Reacciones",
      "baseStat": 75,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Control Balon",
      "baseStat": 72,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Regates",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Compostura",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheap"
    },
    {
      "category": "Defending",
      "attribute": "Intercepciones",
      "baseStat": 35,
      "capStat": 55,
      "costTier": "Most Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "baseStat": 80,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "baseStat": 40,
      "capStat": 65,
      "costTier": "Most Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Robos",
      "baseStat": 40,
      "capStat": 65,
      "costTier": "Most Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Barridas",
      "baseStat": 35,
      "capStat": 55,
      "costTier": "Most Expensive"
    },
    {
      "category": "Physical",
      "attribute": "Salto",
      "baseStat": 75,
      "capStat": 98,
      "costTier": "Cheapest"
    },
    {
      "category": "Physical",
      "attribute": "Resistencia",
      "baseStat": 65,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Fuerza",
      "baseStat": 80,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Physical",
      "attribute": "Agresividad",
      "baseStat": 75,
      "capStat": 98,
      "costTier": "Cheapest"
    }
  ],
  "Creator": [
    {
      "category": "Pace",
      "attribute": "Aceleracion",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Most Expensive"
    },
    {
      "category": "Pace",
      "attribute": "Sprint",
      "baseStat": 65,
      "capStat": 88,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Posicionamiento",
      "baseStat": 70,
      "capStat": 88,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Definicion",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Potencia de Tiro",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Tiros Lejanos",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheapest"
    },
    {
      "category": "Shooting",
      "attribute": "Voleas",
      "baseStat": 68,
      "capStat": 88,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Penales",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Vision",
      "baseStat": 80,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Passing",
      "attribute": "Centros",
      "baseStat": 75,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Pase Corto",
      "baseStat": 80,
      "capStat": 98,
      "costTier": "Cheapest"
    },
    {
      "category": "Passing",
      "attribute": "Pase Largo",
      "baseStat": 75,
      "capStat": 96,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Efecto",
      "baseStat": 78,
      "capStat": 98,
      "costTier": "Cheapest"
    },
    {
      "category": "Dribbling",
      "attribute": "Agilidad",
      "baseStat": 75,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Balance",
      "baseStat": 72,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Reacciones",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Control Balon",
      "baseStat": 80,
      "capStat": 98,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Regates",
      "baseStat": 78,
      "capStat": 96,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Compostura",
      "baseStat": 78,
      "capStat": 96,
      "costTier": "Cheap"
    },
    {
      "category": "Defending",
      "attribute": "Intercepciones",
      "baseStat": 50,
      "capStat": 75,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "baseStat": 45,
      "capStat": 68,
      "costTier": "Most Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "baseStat": 50,
      "capStat": 75,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Robos",
      "baseStat": 50,
      "capStat": 75,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Barridas",
      "baseStat": 40,
      "capStat": 68,
      "costTier": "Most Expensive"
    },
    {
      "category": "Physical",
      "attribute": "Salto",
      "baseStat": 55,
      "capStat": 80,
      "costTier": "Expensive"
    },
    {
      "category": "Physical",
      "attribute": "Resistencia",
      "baseStat": 70,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Fuerza",
      "baseStat": 60,
      "capStat": 82,
      "costTier": "Expensive"
    },
    {
      "category": "Physical",
      "attribute": "Agresividad",
      "baseStat": 60,
      "capStat": 82,
      "costTier": "Expensive"
    }
  ],
  "Progressor": [
    {
      "category": "Pace",
      "attribute": "Aceleracion",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Expensive"
    },
    {
      "category": "Pace",
      "attribute": "Sprint",
      "baseStat": 72,
      "capStat": 92,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Posicionamiento",
      "baseStat": 45,
      "capStat": 65,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Definicion",
      "baseStat": 40,
      "capStat": 62,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Potencia de Tiro",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Tiros Lejanos",
      "baseStat": 50,
      "capStat": 72,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Voleas",
      "baseStat": 45,
      "capStat": 65,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Penales",
      "baseStat": 50,
      "capStat": 72,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Vision",
      "baseStat": 72,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Centros",
      "baseStat": 60,
      "capStat": 82,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Pase Corto",
      "baseStat": 78,
      "capStat": 96,
      "costTier": "Cheapest"
    },
    {
      "category": "Passing",
      "attribute": "Pase Largo",
      "baseStat": 80,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Passing",
      "attribute": "Efecto",
      "baseStat": 60,
      "capStat": 80,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Agilidad",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Balance",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Reacciones",
      "baseStat": 75,
      "capStat": 96,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Control Balon",
      "baseStat": 75,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Regates",
      "baseStat": 68,
      "capStat": 88,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Compostura",
      "baseStat": 80,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Defending",
      "attribute": "Intercepciones",
      "baseStat": 78,
      "capStat": 98,
      "costTier": "Cheapest"
    },
    {
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheap"
    },
    {
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "baseStat": 80,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Defending",
      "attribute": "Robos",
      "baseStat": 78,
      "capStat": 98,
      "costTier": "Cheapest"
    },
    {
      "category": "Defending",
      "attribute": "Barridas",
      "baseStat": 75,
      "capStat": 96,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Salto",
      "baseStat": 72,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Resistencia",
      "baseStat": 72,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Fuerza",
      "baseStat": 76,
      "capStat": 96,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Agresividad",
      "baseStat": 72,
      "capStat": 94,
      "costTier": "Cheap"
    }
  ],
  "Marauder": [
    {
      "category": "Pace",
      "attribute": "Aceleracion",
      "baseStat": 78,
      "capStat": 98,
      "costTier": "Expensive"
    },
    {
      "category": "Pace",
      "attribute": "Sprint",
      "baseStat": 80,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Shooting",
      "attribute": "Posicionamiento",
      "baseStat": 65,
      "capStat": 82,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Definicion",
      "baseStat": 55,
      "capStat": 75,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Potencia de Tiro",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Tiros Lejanos",
      "baseStat": 60,
      "capStat": 82,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Voleas",
      "baseStat": 55,
      "capStat": 75,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Penales",
      "baseStat": 55,
      "capStat": 75,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Vision",
      "baseStat": 68,
      "capStat": 88,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Centros",
      "baseStat": 78,
      "capStat": 98,
      "costTier": "Cheapest"
    },
    {
      "category": "Passing",
      "attribute": "Pase Corto",
      "baseStat": 75,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Pase Largo",
      "baseStat": 68,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Efecto",
      "baseStat": 70,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Agilidad",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Balance",
      "baseStat": 72,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Reacciones",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Control Balon",
      "baseStat": 75,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Regates",
      "baseStat": 74,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Compostura",
      "baseStat": 70,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Defending",
      "attribute": "Intercepciones",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheap"
    },
    {
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "baseStat": 72,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Defending",
      "attribute": "Robos",
      "baseStat": 75,
      "capStat": 96,
      "costTier": "Cheap"
    },
    {
      "category": "Defending",
      "attribute": "Barridas",
      "baseStat": 78,
      "capStat": 98,
      "costTier": "Cheapest"
    },
    {
      "category": "Physical",
      "attribute": "Salto",
      "baseStat": 70,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Resistencia",
      "baseStat": 80,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Physical",
      "attribute": "Fuerza",
      "baseStat": 70,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Agresividad",
      "baseStat": 75,
      "capStat": 96,
      "costTier": "Cheap"
    }
  ],
  "Recycler": [
    {
      "category": "Pace",
      "attribute": "Aceleracion",
      "baseStat": 68,
      "capStat": 88,
      "costTier": "Expensive"
    },
    {
      "category": "Pace",
      "attribute": "Sprint",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Posicionamiento",
      "baseStat": 55,
      "capStat": 75,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Definicion",
      "baseStat": 50,
      "capStat": 70,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Potencia de Tiro",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Shooting",
      "attribute": "Tiros Lejanos",
      "baseStat": 65,
      "capStat": 88,
      "costTier": "Cheapest"
    },
    {
      "category": "Shooting",
      "attribute": "Voleas",
      "baseStat": 50,
      "capStat": 70,
      "costTier": "Most Expensive"
    },
    {
      "category": "Shooting",
      "attribute": "Penales",
      "baseStat": 55,
      "capStat": 75,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Vision",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Centros",
      "baseStat": 60,
      "capStat": 80,
      "costTier": "Expensive"
    },
    {
      "category": "Passing",
      "attribute": "Pase Corto",
      "baseStat": 78,
      "capStat": 96,
      "costTier": "Cheapest"
    },
    {
      "category": "Passing",
      "attribute": "Pase Largo",
      "baseStat": 75,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Passing",
      "attribute": "Efecto",
      "baseStat": 60,
      "capStat": 82,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Agilidad",
      "baseStat": 65,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Dribbling",
      "attribute": "Balance",
      "baseStat": 70,
      "capStat": 90,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Reacciones",
      "baseStat": 75,
      "capStat": 96,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Control Balon",
      "baseStat": 72,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Regates",
      "baseStat": 68,
      "capStat": 88,
      "costTier": "Cheap"
    },
    {
      "category": "Dribbling",
      "attribute": "Compostura",
      "baseStat": 75,
      "capStat": 96,
      "costTier": "Cheap"
    },
    {
      "category": "Defending",
      "attribute": "Intercepciones",
      "baseStat": 80,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "baseStat": 68,
      "capStat": 88,
      "costTier": "Cheap"
    },
    {
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "baseStat": 78,
      "capStat": 98,
      "costTier": "Cheapest"
    },
    {
      "category": "Defending",
      "attribute": "Robos",
      "baseStat": 78,
      "capStat": 98,
      "costTier": "Cheapest"
    },
    {
      "category": "Defending",
      "attribute": "Barridas",
      "baseStat": 72,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Salto",
      "baseStat": 70,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Resistencia",
      "baseStat": 80,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Physical",
      "attribute": "Fuerza",
      "baseStat": 78,
      "capStat": 98,
      "costTier": "Cheapest"
    },
    {
      "category": "Physical",
      "attribute": "Agresividad",
      "baseStat": 78,
      "capStat": 98,
      "costTier": "Cheap"
    }
  ],
  "Shot Stopper": [
    {
      "category": "Goalkeeping",
      "attribute": "GK_Estirada",
      "baseStat": 78,
      "capStat": 98,
      "costTier": "Cheapest"
    },
    {
      "category": "Goalkeeping",
      "attribute": "GK_Paradas",
      "baseStat": 78,
      "capStat": 98,
      "costTier": "Cheapest"
    },
    {
      "category": "Goalkeeping",
      "attribute": "GK_Saque",
      "baseStat": 60,
      "capStat": 85,
      "costTier": "Expensive"
    },
    {
      "category": "Goalkeeping",
      "attribute": "GK_Reflejos",
      "baseStat": 82,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Goalkeeping",
      "attribute": "GK_Colocacion",
      "baseStat": 76,
      "capStat": 96,
      "costTier": "Cheap"
    },
    {
      "category": "Pace",
      "attribute": "Aceleracion",
      "baseStat": 60,
      "capStat": 85,
      "costTier": "Cheapest"
    },
    {
      "category": "Pace",
      "attribute": "Sprint",
      "baseStat": 55,
      "capStat": 80,
      "costTier": "Expensive"
    },
    {
      "category": "Physical",
      "attribute": "Salto",
      "baseStat": 75,
      "capStat": 98,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Fuerza",
      "baseStat": 70,
      "capStat": 92,
      "costTier": "Cheap"
    },
    {
      "category": "Physical",
      "attribute": "Reacciones",
      "baseStat": 78,
      "capStat": 98,
      "costTier": "Cheapest"
    }
  ],
  "Sweeper Keeper": [
    {
      "category": "Goalkeeping",
      "attribute": "GK_Estirada",
      "baseStat": 74,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Goalkeeping",
      "attribute": "GK_Paradas",
      "baseStat": 74,
      "capStat": 94,
      "costTier": "Cheap"
    },
    {
      "category": "Goalkeeping",
      "attribute": "GK_Saque",
      "baseStat": 80,
      "capStat": 99,
      "costTier": "Cheapest"
    },
    {
      "category": "Goalkeeping",
      "attribute": "GK_Reflejos",
      "baseStat": 76,
      "capStat": 96,
      "costTier": "Cheap"
    },
    {
      "category": "Goalkeeping",
      "attribute": "GK_Colocacion",
      "baseStat": 78,
      "capStat": 98,
      "costTier": "Cheapest"
    },
    {
      "category": "Pace",
      "attribute": "Aceleracion",
      "baseStat": 65,
      "capStat": 88,
      "costTier": "Cheapest"
    },
    {
      "category": "Pace",
      "attribute": "Sprint",
      "baseStat": 65,
      "capStat": 88,
      "costTier": "Cheapest"
    },
    {
      "category": "Passing",
      "attribute": "Pase Corto",
      "baseStat": 75,
      "capStat": 95,
      "costTier": "Cheapest"
    },
    {
      "category": "Passing",
      "attribute": "Pase Largo",
      "baseStat": 78,
      "capStat": 98,
      "costTier": "Cheapest"
    },
    {
      "category": "Physical",
      "attribute": "Reacciones",
      "baseStat": 76,
      "capStat": 96,
      "costTier": "Cheapest"
    }
  ]
};

export function getArchetypeAttributes(name: string): ArchetypeAttribute[] {
  return ATTRIBUTES_BY_ARCHETYPE[name] ?? [];
}

/** All attribute names referenced by any archetype (stable order). */
export const ALL_ATTRIBUTES: string[] = Array.from(
  new Set(Object.values(ATTRIBUTES_BY_ARCHETYPE).flat().map((a) => a.attribute)),
);

export const CATEGORIES_BY_ARCHETYPE: Record<string, CategoryName[]> = Object.fromEntries(
  Object.entries(ATTRIBUTES_BY_ARCHETYPE).map(([name, attrs]) => [
    name,
    Array.from(new Set(attrs.map((a) => a.category))),
  ]),
);
