// AUTO-GENERATED by scripts/generate-data.mjs from raw-data/. Do not edit by hand.
import type { Archetype } from "@/types";

export const ARCHETYPES: Archetype[] = [
  {
    "id": 1,
    "name": "Finisher",
    "role": "Striker",
    "primary_position": "LW / ST",
    "signature_playstyle_plus": "Low Driven Shot",
    "specializations": [
      "Chip Shot",
      "Relentless",
      "Gamechanger"
    ],
    "inspired_by": "Alex Morgan",
    "min_height": 164,
    "max_height": 190,
    "default_height": 177,
    "min_weight": 70,
    "max_weight": 90,
    "default_weight": 80,
    "base_ap": 962
  },
  {
    "id": 2,
    "name": "Target",
    "role": "Target Forward",
    "primary_position": "CF / ST",
    "signature_playstyle_plus": "Precision Header",
    "specializations": [
      "Acrobatic",
      "Incisive Pass",
      "Enforcer"
    ],
    "inspired_by": "Zlatan Ibrahimovic",
    "min_height": 177,
    "max_height": 195,
    "default_height": 186,
    "min_weight": 80,
    "max_weight": 100,
    "default_weight": 90,
    "base_ap": 962
  },
  {
    "id": 3,
    "name": "Magician",
    "role": "Forward / Attacking Mid",
    "primary_position": "CAM / CF / ST",
    "signature_playstyle_plus": "Technical",
    "specializations": [
      "First Touch",
      "Power Shot",
      "Incisive Pass"
    ],
    "inspired_by": "Ronaldinho",
    "min_height": 162,
    "max_height": 188,
    "default_height": 175,
    "min_weight": 60,
    "max_weight": 80,
    "default_weight": 70,
    "base_ap": 962
  },
  {
    "id": 4,
    "name": "Spark",
    "role": "Winger",
    "primary_position": "LW / RW",
    "signature_playstyle_plus": "Trickster",
    "specializations": [
      "Quick Step",
      "Whipped Pass",
      "Chip Shot"
    ],
    "inspired_by": "Luis Figo",
    "min_height": 162,
    "max_height": 188,
    "default_height": 175,
    "min_weight": 60,
    "max_weight": 80,
    "default_weight": 70,
    "base_ap": 962
  },
  {
    "id": 5,
    "name": "Creator",
    "role": "Midfielder",
    "primary_position": "CM",
    "signature_playstyle_plus": "Incisive Pass",
    "specializations": [
      "Whipped Pass",
      "Dead Ball",
      "Power Shot"
    ],
    "inspired_by": "Andres Iniesta",
    "min_height": 162,
    "max_height": 188,
    "default_height": 175,
    "min_weight": 65,
    "max_weight": 85,
    "default_weight": 75,
    "base_ap": 962
  },
  {
    "id": 6,
    "name": "Maestro",
    "role": "Midfielder",
    "primary_position": "CM / CAM",
    "signature_playstyle_plus": "Pinged Pass",
    "specializations": [
      "Technical",
      "First Touch",
      "Relentless"
    ],
    "inspired_by": "Toni Kroos",
    "min_height": 162,
    "max_height": 188,
    "default_height": 175,
    "min_weight": 65,
    "max_weight": 85,
    "default_weight": 75,
    "base_ap": 962
  },
  {
    "id": 7,
    "name": "Disruptor",
    "role": "Defensive Midfielder",
    "primary_position": "CDM",
    "signature_playstyle_plus": "Jockey",
    "specializations": [
      "Intercept",
      "Slide Tackle",
      "Bruiser"
    ],
    "inspired_by": "Roy Keane",
    "min_height": 168,
    "max_height": 188,
    "default_height": 178,
    "min_weight": 65,
    "max_weight": 85,
    "default_weight": 75,
    "base_ap": 962
  },
  {
    "id": 8,
    "name": "Recycler",
    "role": "Defensive Midfielder",
    "primary_position": "CDM / CM",
    "signature_playstyle_plus": "Intercept",
    "specializations": [
      "Pinged Pass",
      "Enforcer",
      "Anticipate"
    ],
    "inspired_by": "Claude Makelele",
    "min_height": 172,
    "max_height": 192,
    "default_height": 182,
    "min_weight": 65,
    "max_weight": 85,
    "default_weight": 75,
    "base_ap": 962
  },
  {
    "id": 9,
    "name": "Boss",
    "role": "Defender",
    "primary_position": "CB",
    "signature_playstyle_plus": "Bruiser",
    "specializations": [
      "Slide Tackle",
      "Press Proven",
      "Block"
    ],
    "inspired_by": "Nemanja Vidic",
    "min_height": 180,
    "max_height": 196,
    "default_height": 188,
    "min_weight": 80,
    "max_weight": 100,
    "default_weight": 90,
    "base_ap": 962
  },
  {
    "id": 10,
    "name": "Progressor",
    "role": "Defender",
    "primary_position": "CB / LB",
    "signature_playstyle_plus": "Long Ball Pass",
    "specializations": [
      "Jockey",
      "Pinged Pass",
      "Quick Step"
    ],
    "inspired_by": "Fernando Hierro",
    "min_height": 177,
    "max_height": 195,
    "default_height": 186,
    "min_weight": 75,
    "max_weight": 95,
    "default_weight": 85,
    "base_ap": 962
  },
  {
    "id": 11,
    "name": "Marauder",
    "role": "Full-back",
    "primary_position": "LWB / RWB",
    "signature_playstyle_plus": "Quick Step",
    "specializations": [
      "Slide Tackle",
      "Rapid",
      "Bruiser"
    ],
    "inspired_by": "Cafu",
    "min_height": 168,
    "max_height": 188,
    "default_height": 178,
    "min_weight": 65,
    "max_weight": 85,
    "default_weight": 75,
    "base_ap": 962
  },
  {
    "id": 12,
    "name": "Shot Stopper",
    "role": "Goalkeeper",
    "primary_position": "GK",
    "signature_playstyle_plus": "Far Reach",
    "specializations": [
      "Cross Claimer",
      "1v1 Close Down",
      "Deflector"
    ],
    "inspired_by": "Gianluigi Buffon",
    "min_height": 179,
    "max_height": 197,
    "default_height": 188,
    "min_weight": 80,
    "max_weight": 100,
    "default_weight": 90,
    "base_ap": 962
  },
  {
    "id": 13,
    "name": "Sweeper Keeper",
    "role": "Goalkeeper",
    "primary_position": "GK",
    "signature_playstyle_plus": "Footwork",
    "specializations": [
      "Far Throw",
      "Long Ball Pass",
      "Press Proven"
    ],
    "inspired_by": "Edwin van der Sar",
    "min_height": 184,
    "max_height": 200,
    "default_height": 192,
    "min_weight": 80,
    "max_weight": 100,
    "default_weight": 90,
    "base_ap": 962
  }
];

export const DEFAULT_ARCHETYPE = ARCHETYPES[0].name;

export const ARCHETYPE_BY_NAME: Record<string, Archetype> = Object.fromEntries(
  ARCHETYPES.map((a) => [a.name, a]),
);

export function getArchetype(name: string): Archetype | undefined {
  return ARCHETYPE_BY_NAME[name];
}
