// AUTO-GENERATED by scripts/generate-data.mjs from raw-data/. Do not edit by hand.
import type { ArchetypeMastery } from "@/types";

export const ARCHETYPE_MASTERIES: ArchetypeMastery[] = [
  {
    "archetype": "Finisher",
    "stat_1": "Compostura",
    "bonus_1": 1,
    "stat_2": "Definicion",
    "bonus_2": 2
  },
  {
    "archetype": "Target",
    "stat_1": "Balance",
    "bonus_1": 1,
    "stat_2": "Salto",
    "bonus_2": 2
  },
  {
    "archetype": "Magician",
    "stat_1": "Efecto",
    "bonus_1": 1,
    "stat_2": "Aceleracion",
    "bonus_2": 2
  },
  {
    "archetype": "Spark",
    "stat_1": "Centros",
    "bonus_1": 1,
    "stat_2": "Regates",
    "bonus_2": 2
  },
  {
    "archetype": "Creator",
    "stat_1": "Precision Cabeza",
    "bonus_1": 1,
    "stat_2": "Vision",
    "bonus_2": 2
  },
  {
    "archetype": "Maestro",
    "stat_1": "Reacciones",
    "bonus_1": 1,
    "stat_2": "Control Balon",
    "bonus_2": 2
  },
  {
    "archetype": "Disruptor",
    "stat_1": "Resistencia",
    "bonus_1": 1,
    "stat_2": "Intercepciones",
    "bonus_2": 2
  },
  {
    "archetype": "Recycler",
    "stat_1": "Percepcion Defensiva",
    "bonus_1": 0,
    "stat_2": "Pase Corto",
    "bonus_2": 2
  },
  {
    "archetype": "Boss",
    "stat_1": "Agresividad",
    "bonus_1": 1,
    "stat_2": "Fuerza",
    "bonus_2": 2
  },
  {
    "archetype": "Progressor",
    "stat_1": "Pase Largo",
    "bonus_1": 1,
    "stat_2": "Robos",
    "bonus_2": 2
  },
  {
    "archetype": "Marauder",
    "stat_1": "Barridas",
    "bonus_1": 1,
    "stat_2": "Sprint",
    "bonus_2": 2
  },
  {
    "archetype": "Shot Stopper",
    "stat_1": "GK_Colocacion",
    "bonus_1": 1,
    "stat_2": "GK_Reflejos",
    "bonus_2": 2
  },
  {
    "archetype": "Sweeper Keeper",
    "stat_1": "GK_Paradas",
    "bonus_1": 1,
    "stat_2": "GK_Estirada",
    "bonus_2": 2
  }
];

export const MASTERY_BY_ARCHETYPE: Record<string, ArchetypeMastery> =
  Object.fromEntries(ARCHETYPE_MASTERIES.map((m) => [m.archetype, m]));

export function getMastery(name: string): ArchetypeMastery | undefined {
  return MASTERY_BY_ARCHETYPE[name];
}
