// AUTO-GENERATED by scripts/generate-data.mjs from raw-data/. Do not edit by hand.
import type { Archetype } from "@/types";

export const ARCHETYPES: Archetype[] = [
  {
    "id": 1,
    "name": "Finisher",
    "role": "Delantero",
    "primary_position": "DC / SD",
    "signature_playstyle_plus": "Low Driven Shot",
    "specializations": [
      "Chip Shot",
      "Relentless",
      "Gamechanger"
    ],
    "inspired_by": "Alex Morgan",
    "min_height": 165,
    "max_height": 195,
    "default_height": 180,
    "min_weight": 55,
    "max_weight": 95,
    "default_weight": 75,
    "base_ap": 962
  },
  {
    "id": 2,
    "name": "Target",
    "role": "Delantero Boya",
    "primary_position": "DC",
    "signature_playstyle_plus": "Precision Header",
    "specializations": [
      "Acrobatic",
      "Incisive Pass",
      "Enforcer"
    ],
    "inspired_by": "Zlatan Ibrahimovic",
    "min_height": 182,
    "max_height": 205,
    "default_height": 192,
    "min_weight": 75,
    "max_weight": 115,
    "default_weight": 88,
    "base_ap": 962
  },
  {
    "id": 3,
    "name": "Magician",
    "role": "Delantero / Mediapunta",
    "primary_position": "MCO / EI / ED",
    "signature_playstyle_plus": "Technical",
    "specializations": [
      "First Touch",
      "Power Shot",
      "Incisive Pass"
    ],
    "inspired_by": "Ronaldinho",
    "min_height": 160,
    "max_height": 188,
    "default_height": 172,
    "min_weight": 50,
    "max_weight": 85,
    "default_weight": 68,
    "base_ap": 962
  },
  {
    "id": 4,
    "name": "Spark",
    "role": "Extremo",
    "primary_position": "EI / ED / MD / MI",
    "signature_playstyle_plus": "Trickster",
    "specializations": [
      "Quick Step",
      "Whipped Pass",
      "Chip Shot"
    ],
    "inspired_by": "Luis Figo",
    "min_height": 155,
    "max_height": 185,
    "default_height": 168,
    "min_weight": 45,
    "max_weight": 80,
    "default_weight": 64,
    "base_ap": 962
  },
  {
    "id": 5,
    "name": "Creator",
    "role": "Mediocampista",
    "primary_position": "MCO / MC",
    "signature_playstyle_plus": "Incisive Pass",
    "specializations": [
      "Whipped Pass",
      "Dead Ball",
      "Power Shot"
    ],
    "inspired_by": "Andres Iniesta",
    "min_height": 162,
    "max_height": 188,
    "default_height": 174,
    "min_weight": 52,
    "max_weight": 85,
    "default_weight": 70,
    "base_ap": 962
  },
  {
    "id": 6,
    "name": "Maestro",
    "role": "Mediocampista",
    "primary_position": "MC",
    "signature_playstyle_plus": "Pinged Pass",
    "specializations": [
      "Technical",
      "First Touch",
      "Relentless"
    ],
    "inspired_by": "Toni Kroos",
    "min_height": 168,
    "max_height": 192,
    "default_height": 178,
    "min_weight": 60,
    "max_weight": 90,
    "default_weight": 74,
    "base_ap": 962
  },
  {
    "id": 7,
    "name": "Disruptor",
    "role": "Mediocampista Defensivo",
    "primary_position": "MCD",
    "signature_playstyle_plus": "Jockey",
    "specializations": [
      "Intercept",
      "Slide Tackle",
      "Bruiser"
    ],
    "inspired_by": "Roy Keane",
    "min_height": 172,
    "max_height": 196,
    "default_height": 184,
    "min_weight": 68,
    "max_weight": 100,
    "default_weight": 80,
    "base_ap": 962
  },
  {
    "id": 8,
    "name": "Recycler",
    "role": "Mediocampista Defensivo",
    "primary_position": "MCD / MC",
    "signature_playstyle_plus": "Intercept",
    "specializations": [
      "Pinged Pass",
      "Enforcer",
      "Anticipate"
    ],
    "inspired_by": "Claude Makelele",
    "min_height": 168,
    "max_height": 192,
    "default_height": 176,
    "min_weight": 62,
    "max_weight": 92,
    "default_weight": 73,
    "base_ap": 962
  },
  {
    "id": 9,
    "name": "Boss",
    "role": "Defensa",
    "primary_position": "DFC",
    "signature_playstyle_plus": "Bruiser",
    "specializations": [
      "Slide Tackle",
      "Press Proven",
      "Block"
    ],
    "inspired_by": "Nemanja Vidic",
    "min_height": 180,
    "max_height": 205,
    "default_height": 188,
    "min_weight": 75,
    "max_weight": 115,
    "default_weight": 85,
    "base_ap": 962
  },
  {
    "id": 10,
    "name": "Progressor",
    "role": "Defensa",
    "primary_position": "DFC",
    "signature_playstyle_plus": "Long Ball Pass",
    "specializations": [
      "Jockey",
      "Pinged Pass",
      "Quick Step"
    ],
    "inspired_by": "Fernando Hierro",
    "min_height": 178,
    "max_height": 201,
    "default_height": 185,
    "min_weight": 70,
    "max_weight": 105,
    "default_weight": 80,
    "base_ap": 962
  },
  {
    "id": 11,
    "name": "Marauder",
    "role": "Lateral",
    "primary_position": "LD / LI",
    "signature_playstyle_plus": "Quick Step",
    "specializations": [
      "Slide Tackle",
      "Rapid",
      "Bruiser"
    ],
    "inspired_by": "Cafu",
    "min_height": 165,
    "max_height": 188,
    "default_height": 175,
    "min_weight": 58,
    "max_weight": 88,
    "default_weight": 72,
    "base_ap": 962
  }
];

export const DEFAULT_ARCHETYPE = ARCHETYPES[0].name;

export const ARCHETYPE_BY_NAME: Record<string, Archetype> = Object.fromEntries(
  ARCHETYPES.map((a) => [a.name, a]),
);

export function getArchetype(name: string): Archetype | undefined {
  return ARCHETYPE_BY_NAME[name];
}
