// AUTO-GENERATED by scripts/generate-data.mjs from raw-data/. Do not edit by hand.
import type { ArchetypeAttribute } from "@/types";

export const ATTRIBUTES_BY_ARCHETYPE: Record<string, ArchetypeAttribute[]> = {
  "Finisher": [
    {
      "archetype": "Finisher",
      "category": "Pace",
      "attribute": "Aceleracion",
      "base_stat": 75,
      "cap_stat": 95,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Finisher",
      "category": "Pace",
      "attribute": "Sprint",
      "base_stat": 75,
      "cap_stat": 95,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Finisher",
      "category": "Scoring",
      "attribute": "Posicionamiento",
      "base_stat": 80,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Finisher",
      "category": "Scoring",
      "attribute": "Definicion",
      "base_stat": 75,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Finisher",
      "category": "Scoring",
      "attribute": "Potencia Tiro",
      "base_stat": 75,
      "cap_stat": 97,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Finisher",
      "category": "Scoring",
      "attribute": "Tiros Lejanos",
      "base_stat": 60,
      "cap_stat": 88,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Finisher",
      "category": "Scoring",
      "attribute": "Voleas",
      "base_stat": 75,
      "cap_stat": 95,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Finisher",
      "category": "Scoring",
      "attribute": "Penales",
      "base_stat": 75,
      "cap_stat": 92,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Finisher",
      "category": "Passing",
      "attribute": "Vision",
      "base_stat": 65,
      "cap_stat": 84,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Finisher",
      "category": "Passing",
      "attribute": "Centros",
      "base_stat": 55,
      "cap_stat": 75,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Finisher",
      "category": "Passing",
      "attribute": "Precision Faltas",
      "base_stat": 65,
      "cap_stat": 82,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Finisher",
      "category": "Passing",
      "attribute": "Pase Corto",
      "base_stat": 70,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Finisher",
      "category": "Passing",
      "attribute": "Pase Largo",
      "base_stat": 50,
      "cap_stat": 75,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Finisher",
      "category": "Passing",
      "attribute": "Efecto",
      "base_stat": 70,
      "cap_stat": 85,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Finisher",
      "category": "Ball Control",
      "attribute": "Agilidad",
      "base_stat": 75,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Finisher",
      "category": "Ball Control",
      "attribute": "Balance",
      "base_stat": 75,
      "cap_stat": 88,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Finisher",
      "category": "Ball Control",
      "attribute": "Reacciones",
      "base_stat": 75,
      "cap_stat": 96,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Finisher",
      "category": "Ball Control",
      "attribute": "Control Balon",
      "base_stat": 75,
      "cap_stat": 95,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Finisher",
      "category": "Ball Control",
      "attribute": "Regates",
      "base_stat": 70,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Finisher",
      "category": "Ball Control",
      "attribute": "Compostura",
      "base_stat": 75,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Finisher",
      "category": "Defending",
      "attribute": "Intercepciones",
      "base_stat": 60,
      "cap_stat": 75,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Finisher",
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "base_stat": 75,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Finisher",
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "base_stat": 55,
      "cap_stat": 70,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Finisher",
      "category": "Defending",
      "attribute": "Robos",
      "base_stat": 50,
      "cap_stat": 68,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Finisher",
      "category": "Defending",
      "attribute": "Barridas",
      "base_stat": 40,
      "cap_stat": 60,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Finisher",
      "category": "Physical",
      "attribute": "Salto",
      "base_stat": 65,
      "cap_stat": 85,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Finisher",
      "category": "Physical",
      "attribute": "Resistencia",
      "base_stat": 65,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Finisher",
      "category": "Physical",
      "attribute": "Fuerza",
      "base_stat": 70,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Finisher",
      "category": "Physical",
      "attribute": "Agresividad",
      "base_stat": 65,
      "cap_stat": 82,
      "cost_tier": "Expensive"
    }
  ],
  "Target": [
    {
      "archetype": "Target",
      "category": "Pace",
      "attribute": "Aceleracion",
      "base_stat": 65,
      "cap_stat": 90,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Target",
      "category": "Pace",
      "attribute": "Sprint",
      "base_stat": 68,
      "cap_stat": 92,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Target",
      "category": "Scoring",
      "attribute": "Posicionamiento",
      "base_stat": 78,
      "cap_stat": 95,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Target",
      "category": "Scoring",
      "attribute": "Definicion",
      "base_stat": 74,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Target",
      "category": "Scoring",
      "attribute": "Potencia Tiro",
      "base_stat": 78,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Target",
      "category": "Scoring",
      "attribute": "Tiros Lejanos",
      "base_stat": 65,
      "cap_stat": 86,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Target",
      "category": "Scoring",
      "attribute": "Voleas",
      "base_stat": 72,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Target",
      "category": "Scoring",
      "attribute": "Penales",
      "base_stat": 70,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Target",
      "category": "Passing",
      "attribute": "Vision",
      "base_stat": 62,
      "cap_stat": 82,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Target",
      "category": "Passing",
      "attribute": "Centros",
      "base_stat": 50,
      "cap_stat": 70,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Target",
      "category": "Passing",
      "attribute": "Precision Faltas",
      "base_stat": 55,
      "cap_stat": 75,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Target",
      "category": "Passing",
      "attribute": "Pase Corto",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Target",
      "category": "Passing",
      "attribute": "Pase Largo",
      "base_stat": 52,
      "cap_stat": 78,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Target",
      "category": "Passing",
      "attribute": "Efecto",
      "base_stat": 58,
      "cap_stat": 78,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Target",
      "category": "Ball Control",
      "attribute": "Agilidad",
      "base_stat": 60,
      "cap_stat": 80,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Target",
      "category": "Ball Control",
      "attribute": "Balance",
      "base_stat": 62,
      "cap_stat": 82,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Target",
      "category": "Ball Control",
      "attribute": "Reacciones",
      "base_stat": 72,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Target",
      "category": "Ball Control",
      "attribute": "Control Balon",
      "base_stat": 74,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Target",
      "category": "Ball Control",
      "attribute": "Regates",
      "base_stat": 66,
      "cap_stat": 85,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Target",
      "category": "Ball Control",
      "attribute": "Compostura",
      "base_stat": 76,
      "cap_stat": 95,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Target",
      "category": "Defending",
      "attribute": "Intercepciones",
      "base_stat": 55,
      "cap_stat": 72,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Target",
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "base_stat": 82,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Target",
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "base_stat": 58,
      "cap_stat": 75,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Target",
      "category": "Defending",
      "attribute": "Robos",
      "base_stat": 55,
      "cap_stat": 72,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Target",
      "category": "Defending",
      "attribute": "Barridas",
      "base_stat": 42,
      "cap_stat": 62,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Target",
      "category": "Physical",
      "attribute": "Salto",
      "base_stat": 76,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Target",
      "category": "Physical",
      "attribute": "Resistencia",
      "base_stat": 70,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Target",
      "category": "Physical",
      "attribute": "Fuerza",
      "base_stat": 82,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Target",
      "category": "Physical",
      "attribute": "Agresividad",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    }
  ],
  "Spark": [
    {
      "archetype": "Spark",
      "category": "Pace",
      "attribute": "Aceleracion",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Spark",
      "category": "Pace",
      "attribute": "Sprint",
      "base_stat": 82,
      "cap_stat": 99,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Spark",
      "category": "Scoring",
      "attribute": "Posicionamiento",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Spark",
      "category": "Scoring",
      "attribute": "Definicion",
      "base_stat": 68,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Spark",
      "category": "Scoring",
      "attribute": "Potencia Tiro",
      "base_stat": 70,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Spark",
      "category": "Scoring",
      "attribute": "Tiros Lejanos",
      "base_stat": 62,
      "cap_stat": 84,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Spark",
      "category": "Scoring",
      "attribute": "Voleas",
      "base_stat": 64,
      "cap_stat": 82,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Spark",
      "category": "Scoring",
      "attribute": "Penales",
      "base_stat": 65,
      "cap_stat": 82,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Spark",
      "category": "Passing",
      "attribute": "Vision",
      "base_stat": 70,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Spark",
      "category": "Passing",
      "attribute": "Centros",
      "base_stat": 76,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Spark",
      "category": "Passing",
      "attribute": "Precision Faltas",
      "base_stat": 64,
      "cap_stat": 84,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Spark",
      "category": "Passing",
      "attribute": "Pase Corto",
      "base_stat": 74,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Spark",
      "category": "Passing",
      "attribute": "Pase Largo",
      "base_stat": 62,
      "cap_stat": 82,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Spark",
      "category": "Passing",
      "attribute": "Efecto",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Spark",
      "category": "Ball Control",
      "attribute": "Agilidad",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Spark",
      "category": "Ball Control",
      "attribute": "Balance",
      "base_stat": 80,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Spark",
      "category": "Ball Control",
      "attribute": "Reacciones",
      "base_stat": 74,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Spark",
      "category": "Ball Control",
      "attribute": "Control Balon",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Spark",
      "category": "Ball Control",
      "attribute": "Regates",
      "base_stat": 82,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Spark",
      "category": "Ball Control",
      "attribute": "Compostura",
      "base_stat": 70,
      "cap_stat": 88,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Spark",
      "category": "Defending",
      "attribute": "Intercepciones",
      "base_stat": 50,
      "cap_stat": 68,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Spark",
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "base_stat": 55,
      "cap_stat": 72,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Spark",
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "base_stat": 48,
      "cap_stat": 65,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Spark",
      "category": "Defending",
      "attribute": "Robos",
      "base_stat": 48,
      "cap_stat": 66,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Spark",
      "category": "Defending",
      "attribute": "Barridas",
      "base_stat": 45,
      "cap_stat": 62,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Spark",
      "category": "Physical",
      "attribute": "Salto",
      "base_stat": 60,
      "cap_stat": 80,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Spark",
      "category": "Physical",
      "attribute": "Resistencia",
      "base_stat": 72,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Spark",
      "category": "Physical",
      "attribute": "Fuerza",
      "base_stat": 58,
      "cap_stat": 78,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Spark",
      "category": "Physical",
      "attribute": "Agresividad",
      "base_stat": 60,
      "cap_stat": 78,
      "cost_tier": "Expensive"
    }
  ],
  "Magician": [
    {
      "archetype": "Magician",
      "category": "Pace",
      "attribute": "Aceleracion",
      "base_stat": 78,
      "cap_stat": 95,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Magician",
      "category": "Pace",
      "attribute": "Sprint",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Magician",
      "category": "Scoring",
      "attribute": "Posicionamiento",
      "base_stat": 75,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Magician",
      "category": "Scoring",
      "attribute": "Definicion",
      "base_stat": 72,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Magician",
      "category": "Scoring",
      "attribute": "Potencia Tiro",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Magician",
      "category": "Scoring",
      "attribute": "Tiros Lejanos",
      "base_stat": 74,
      "cap_stat": 94,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Magician",
      "category": "Scoring",
      "attribute": "Voleas",
      "base_stat": 70,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Magician",
      "category": "Scoring",
      "attribute": "Penales",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Magician",
      "category": "Passing",
      "attribute": "Vision",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Magician",
      "category": "Passing",
      "attribute": "Centros",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Magician",
      "category": "Passing",
      "attribute": "Precision Faltas",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Magician",
      "category": "Passing",
      "attribute": "Pase Corto",
      "base_stat": 80,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Magician",
      "category": "Passing",
      "attribute": "Pase Largo",
      "base_stat": 74,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Magician",
      "category": "Passing",
      "attribute": "Efecto",
      "base_stat": 80,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Magician",
      "category": "Ball Control",
      "attribute": "Agilidad",
      "base_stat": 82,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Magician",
      "category": "Ball Control",
      "attribute": "Balance",
      "base_stat": 78,
      "cap_stat": 95,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Magician",
      "category": "Ball Control",
      "attribute": "Reacciones",
      "base_stat": 76,
      "cap_stat": 95,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Magician",
      "category": "Ball Control",
      "attribute": "Control Balon",
      "base_stat": 82,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Magician",
      "category": "Ball Control",
      "attribute": "Regates",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Magician",
      "category": "Ball Control",
      "attribute": "Compostura",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Magician",
      "category": "Defending",
      "attribute": "Intercepciones",
      "base_stat": 52,
      "cap_stat": 70,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Magician",
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "base_stat": 56,
      "cap_stat": 74,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Magician",
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "base_stat": 50,
      "cap_stat": 68,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Magician",
      "category": "Defending",
      "attribute": "Robos",
      "base_stat": 50,
      "cap_stat": 68,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Magician",
      "category": "Defending",
      "attribute": "Barridas",
      "base_stat": 44,
      "cap_stat": 62,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Magician",
      "category": "Physical",
      "attribute": "Salto",
      "base_stat": 62,
      "cap_stat": 82,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Magician",
      "category": "Physical",
      "attribute": "Resistencia",
      "base_stat": 70,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Magician",
      "category": "Physical",
      "attribute": "Fuerza",
      "base_stat": 60,
      "cap_stat": 80,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Magician",
      "category": "Physical",
      "attribute": "Agresividad",
      "base_stat": 62,
      "cap_stat": 80,
      "cost_tier": "Expensive"
    }
  ],
  "Creator": [
    {
      "archetype": "Creator",
      "category": "Pace",
      "attribute": "Aceleracion",
      "base_stat": 74,
      "cap_stat": 92,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Creator",
      "category": "Pace",
      "attribute": "Sprint",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Creator",
      "category": "Scoring",
      "attribute": "Posicionamiento",
      "base_stat": 74,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Creator",
      "category": "Scoring",
      "attribute": "Definicion",
      "base_stat": 68,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Creator",
      "category": "Scoring",
      "attribute": "Potencia Tiro",
      "base_stat": 72,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Creator",
      "category": "Scoring",
      "attribute": "Tiros Lejanos",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Creator",
      "category": "Scoring",
      "attribute": "Voleas",
      "base_stat": 66,
      "cap_stat": 84,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Creator",
      "category": "Scoring",
      "attribute": "Penales",
      "base_stat": 68,
      "cap_stat": 85,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Creator",
      "category": "Passing",
      "attribute": "Vision",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Creator",
      "category": "Passing",
      "attribute": "Centros",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Creator",
      "category": "Passing",
      "attribute": "Precision Faltas",
      "base_stat": 75,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Creator",
      "category": "Passing",
      "attribute": "Pase Corto",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Creator",
      "category": "Passing",
      "attribute": "Pase Largo",
      "base_stat": 80,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Creator",
      "category": "Passing",
      "attribute": "Efecto",
      "base_stat": 78,
      "cap_stat": 95,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Creator",
      "category": "Ball Control",
      "attribute": "Agilidad",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Creator",
      "category": "Ball Control",
      "attribute": "Balance",
      "base_stat": 74,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Creator",
      "category": "Ball Control",
      "attribute": "Reacciones",
      "base_stat": 76,
      "cap_stat": 95,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Creator",
      "category": "Ball Control",
      "attribute": "Control Balon",
      "base_stat": 80,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Creator",
      "category": "Ball Control",
      "attribute": "Regates",
      "base_stat": 78,
      "cap_stat": 95,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Creator",
      "category": "Ball Control",
      "attribute": "Compostura",
      "base_stat": 78,
      "cap_stat": 95,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Creator",
      "category": "Defending",
      "attribute": "Intercepciones",
      "base_stat": 58,
      "cap_stat": 78,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Creator",
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "base_stat": 58,
      "cap_stat": 76,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Creator",
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "base_stat": 56,
      "cap_stat": 75,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Creator",
      "category": "Defending",
      "attribute": "Robos",
      "base_stat": 56,
      "cap_stat": 75,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Creator",
      "category": "Defending",
      "attribute": "Barridas",
      "base_stat": 48,
      "cap_stat": 68,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Creator",
      "category": "Physical",
      "attribute": "Salto",
      "base_stat": 62,
      "cap_stat": 80,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Creator",
      "category": "Physical",
      "attribute": "Resistencia",
      "base_stat": 74,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Creator",
      "category": "Physical",
      "attribute": "Fuerza",
      "base_stat": 62,
      "cap_stat": 82,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Creator",
      "category": "Physical",
      "attribute": "Agresividad",
      "base_stat": 64,
      "cap_stat": 82,
      "cost_tier": "Expensive"
    }
  ],
  "Maestro": [
    {
      "archetype": "Maestro",
      "category": "Pace",
      "attribute": "Aceleracion",
      "base_stat": 70,
      "cap_stat": 88,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Maestro",
      "category": "Pace",
      "attribute": "Sprint",
      "base_stat": 70,
      "cap_stat": 88,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Maestro",
      "category": "Scoring",
      "attribute": "Posicionamiento",
      "base_stat": 70,
      "cap_stat": 86,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Maestro",
      "category": "Scoring",
      "attribute": "Definicion",
      "base_stat": 66,
      "cap_stat": 84,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Maestro",
      "category": "Scoring",
      "attribute": "Potencia Tiro",
      "base_stat": 74,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Maestro",
      "category": "Scoring",
      "attribute": "Tiros Lejanos",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Maestro",
      "category": "Scoring",
      "attribute": "Voleas",
      "base_stat": 68,
      "cap_stat": 86,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Maestro",
      "category": "Scoring",
      "attribute": "Penales",
      "base_stat": 70,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Maestro",
      "category": "Passing",
      "attribute": "Vision",
      "base_stat": 82,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Maestro",
      "category": "Passing",
      "attribute": "Centros",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Maestro",
      "category": "Passing",
      "attribute": "Precision Faltas",
      "base_stat": 78,
      "cap_stat": 95,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Maestro",
      "category": "Passing",
      "attribute": "Pase Corto",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Maestro",
      "category": "Passing",
      "attribute": "Pase Largo",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Maestro",
      "category": "Passing",
      "attribute": "Efecto",
      "base_stat": 78,
      "cap_stat": 95,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Maestro",
      "category": "Ball Control",
      "attribute": "Agilidad",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Maestro",
      "category": "Ball Control",
      "attribute": "Balance",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Maestro",
      "category": "Ball Control",
      "attribute": "Reacciones",
      "base_stat": 80,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Maestro",
      "category": "Ball Control",
      "attribute": "Control Balon",
      "base_stat": 82,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Maestro",
      "category": "Ball Control",
      "attribute": "Regates",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Maestro",
      "category": "Ball Control",
      "attribute": "Compostura",
      "base_stat": 82,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Maestro",
      "category": "Defending",
      "attribute": "Intercepciones",
      "base_stat": 68,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Maestro",
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "base_stat": 62,
      "cap_stat": 80,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Maestro",
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "base_stat": 66,
      "cap_stat": 86,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Maestro",
      "category": "Defending",
      "attribute": "Robos",
      "base_stat": 66,
      "cap_stat": 86,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Maestro",
      "category": "Defending",
      "attribute": "Barridas",
      "base_stat": 58,
      "cap_stat": 78,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Maestro",
      "category": "Physical",
      "attribute": "Salto",
      "base_stat": 65,
      "cap_stat": 84,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Maestro",
      "category": "Physical",
      "attribute": "Resistencia",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Maestro",
      "category": "Physical",
      "attribute": "Fuerza",
      "base_stat": 68,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Maestro",
      "category": "Physical",
      "attribute": "Agresividad",
      "base_stat": 70,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    }
  ],
  "Disruptor": [
    {
      "archetype": "Disruptor",
      "category": "Pace",
      "attribute": "Aceleracion",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Disruptor",
      "category": "Pace",
      "attribute": "Sprint",
      "base_stat": 74,
      "cap_stat": 92,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Disruptor",
      "category": "Scoring",
      "attribute": "Posicionamiento",
      "base_stat": 60,
      "cap_stat": 78,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Disruptor",
      "category": "Scoring",
      "attribute": "Definicion",
      "base_stat": 58,
      "cap_stat": 76,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Disruptor",
      "category": "Scoring",
      "attribute": "Potencia Tiro",
      "base_stat": 72,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Disruptor",
      "category": "Scoring",
      "attribute": "Tiros Lejanos",
      "base_stat": 64,
      "cap_stat": 82,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Disruptor",
      "category": "Scoring",
      "attribute": "Voleas",
      "base_stat": 58,
      "cap_stat": 75,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Disruptor",
      "category": "Scoring",
      "attribute": "Penales",
      "base_stat": 60,
      "cap_stat": 78,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Disruptor",
      "category": "Passing",
      "attribute": "Vision",
      "base_stat": 68,
      "cap_stat": 86,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Disruptor",
      "category": "Passing",
      "attribute": "Centros",
      "base_stat": 62,
      "cap_stat": 80,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Disruptor",
      "category": "Passing",
      "attribute": "Precision Faltas",
      "base_stat": 60,
      "cap_stat": 78,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Disruptor",
      "category": "Passing",
      "attribute": "Pase Corto",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Disruptor",
      "category": "Passing",
      "attribute": "Pase Largo",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Disruptor",
      "category": "Passing",
      "attribute": "Efecto",
      "base_stat": 62,
      "cap_stat": 80,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Disruptor",
      "category": "Ball Control",
      "attribute": "Agilidad",
      "base_stat": 70,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Disruptor",
      "category": "Ball Control",
      "attribute": "Balance",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Disruptor",
      "category": "Ball Control",
      "attribute": "Reacciones",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Disruptor",
      "category": "Ball Control",
      "attribute": "Control Balon",
      "base_stat": 74,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Disruptor",
      "category": "Ball Control",
      "attribute": "Regates",
      "base_stat": 68,
      "cap_stat": 86,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Disruptor",
      "category": "Ball Control",
      "attribute": "Compostura",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Disruptor",
      "category": "Defending",
      "attribute": "Intercepciones",
      "base_stat": 80,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Disruptor",
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Disruptor",
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Disruptor",
      "category": "Defending",
      "attribute": "Robos",
      "base_stat": 82,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Disruptor",
      "category": "Defending",
      "attribute": "Barridas",
      "base_stat": 80,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Disruptor",
      "category": "Physical",
      "attribute": "Salto",
      "base_stat": 74,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Disruptor",
      "category": "Physical",
      "attribute": "Resistencia",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Disruptor",
      "category": "Physical",
      "attribute": "Fuerza",
      "base_stat": 80,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Disruptor",
      "category": "Physical",
      "attribute": "Agresividad",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    }
  ],
  "Recycler": [
    {
      "archetype": "Recycler",
      "category": "Pace",
      "attribute": "Aceleracion",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Recycler",
      "category": "Pace",
      "attribute": "Sprint",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Recycler",
      "category": "Scoring",
      "attribute": "Posicionamiento",
      "base_stat": 62,
      "cap_stat": 80,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Recycler",
      "category": "Scoring",
      "attribute": "Definicion",
      "base_stat": 56,
      "cap_stat": 75,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Recycler",
      "category": "Scoring",
      "attribute": "Potencia Tiro",
      "base_stat": 68,
      "cap_stat": 85,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Recycler",
      "category": "Scoring",
      "attribute": "Tiros Lejanos",
      "base_stat": 62,
      "cap_stat": 80,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Recycler",
      "category": "Scoring",
      "attribute": "Voleas",
      "base_stat": 56,
      "cap_stat": 74,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Recycler",
      "category": "Scoring",
      "attribute": "Penales",
      "base_stat": 60,
      "cap_stat": 78,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Recycler",
      "category": "Passing",
      "attribute": "Vision",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Recycler",
      "category": "Passing",
      "attribute": "Centros",
      "base_stat": 66,
      "cap_stat": 84,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Recycler",
      "category": "Passing",
      "attribute": "Precision Faltas",
      "base_stat": 62,
      "cap_stat": 80,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Recycler",
      "category": "Passing",
      "attribute": "Pase Corto",
      "base_stat": 82,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Recycler",
      "category": "Passing",
      "attribute": "Pase Largo",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Recycler",
      "category": "Passing",
      "attribute": "Efecto",
      "base_stat": 66,
      "cap_stat": 84,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Recycler",
      "category": "Ball Control",
      "attribute": "Agilidad",
      "base_stat": 74,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Recycler",
      "category": "Ball Control",
      "attribute": "Balance",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Recycler",
      "category": "Ball Control",
      "attribute": "Reacciones",
      "base_stat": 80,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Recycler",
      "category": "Ball Control",
      "attribute": "Control Balon",
      "base_stat": 80,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Recycler",
      "category": "Ball Control",
      "attribute": "Regates",
      "base_stat": 74,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Recycler",
      "category": "Ball Control",
      "attribute": "Compostura",
      "base_stat": 80,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Recycler",
      "category": "Defending",
      "attribute": "Intercepciones",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Recycler",
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "base_stat": 68,
      "cap_stat": 86,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Recycler",
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "base_stat": 82,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Recycler",
      "category": "Defending",
      "attribute": "Robos",
      "base_stat": 80,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Recycler",
      "category": "Defending",
      "attribute": "Barridas",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Recycler",
      "category": "Physical",
      "attribute": "Salto",
      "base_stat": 70,
      "cap_stat": 88,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Recycler",
      "category": "Physical",
      "attribute": "Resistencia",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Recycler",
      "category": "Physical",
      "attribute": "Fuerza",
      "base_stat": 74,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Recycler",
      "category": "Physical",
      "attribute": "Agresividad",
      "base_stat": 76,
      "cap_stat": 95,
      "cost_tier": "Cheap"
    }
  ],
  "Boss": [
    {
      "archetype": "Boss",
      "category": "Pace",
      "attribute": "Aceleracion",
      "base_stat": 66,
      "cap_stat": 88,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Pace",
      "attribute": "Sprint",
      "base_stat": 72,
      "cap_stat": 92,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Scoring",
      "attribute": "Posicionamiento",
      "base_stat": 50,
      "cap_stat": 68,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Scoring",
      "attribute": "Definicion",
      "base_stat": 45,
      "cap_stat": 65,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Scoring",
      "attribute": "Potencia Tiro",
      "base_stat": 65,
      "cap_stat": 85,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Scoring",
      "attribute": "Tiros Lejanos",
      "base_stat": 50,
      "cap_stat": 70,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Scoring",
      "attribute": "Voleas",
      "base_stat": 48,
      "cap_stat": 68,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Scoring",
      "attribute": "Penales",
      "base_stat": 52,
      "cap_stat": 70,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Passing",
      "attribute": "Vision",
      "base_stat": 58,
      "cap_stat": 78,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Passing",
      "attribute": "Centros",
      "base_stat": 48,
      "cap_stat": 68,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Passing",
      "attribute": "Precision Faltas",
      "base_stat": 50,
      "cap_stat": 70,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Passing",
      "attribute": "Pase Corto",
      "base_stat": 70,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Boss",
      "category": "Passing",
      "attribute": "Pase Largo",
      "base_stat": 66,
      "cap_stat": 85,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Passing",
      "attribute": "Efecto",
      "base_stat": 52,
      "cap_stat": 72,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Ball Control",
      "attribute": "Agilidad",
      "base_stat": 58,
      "cap_stat": 78,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Ball Control",
      "attribute": "Balance",
      "base_stat": 60,
      "cap_stat": 80,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Ball Control",
      "attribute": "Reacciones",
      "base_stat": 76,
      "cap_stat": 96,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Boss",
      "category": "Ball Control",
      "attribute": "Control Balon",
      "base_stat": 68,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Boss",
      "category": "Ball Control",
      "attribute": "Regates",
      "base_stat": 58,
      "cap_stat": 78,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Boss",
      "category": "Ball Control",
      "attribute": "Compostura",
      "base_stat": 76,
      "cap_stat": 96,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Boss",
      "category": "Defending",
      "attribute": "Intercepciones",
      "base_stat": 82,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Boss",
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "base_stat": 82,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Boss",
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Boss",
      "category": "Defending",
      "attribute": "Robos",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Boss",
      "category": "Defending",
      "attribute": "Barridas",
      "base_stat": 82,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Boss",
      "category": "Physical",
      "attribute": "Salto",
      "base_stat": 78,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Boss",
      "category": "Physical",
      "attribute": "Resistencia",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Boss",
      "category": "Physical",
      "attribute": "Fuerza",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Boss",
      "category": "Physical",
      "attribute": "Agresividad",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    }
  ],
  "Progressor": [
    {
      "archetype": "Progressor",
      "category": "Pace",
      "attribute": "Aceleracion",
      "base_stat": 70,
      "cap_stat": 90,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Progressor",
      "category": "Pace",
      "attribute": "Sprint",
      "base_stat": 74,
      "cap_stat": 94,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Progressor",
      "category": "Scoring",
      "attribute": "Posicionamiento",
      "base_stat": 52,
      "cap_stat": 70,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Progressor",
      "category": "Scoring",
      "attribute": "Definicion",
      "base_stat": 48,
      "cap_stat": 68,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Progressor",
      "category": "Scoring",
      "attribute": "Potencia Tiro",
      "base_stat": 66,
      "cap_stat": 86,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Progressor",
      "category": "Scoring",
      "attribute": "Tiros Lejanos",
      "base_stat": 54,
      "cap_stat": 74,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Progressor",
      "category": "Scoring",
      "attribute": "Voleas",
      "base_stat": 50,
      "cap_stat": 70,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Progressor",
      "category": "Scoring",
      "attribute": "Penales",
      "base_stat": 54,
      "cap_stat": 72,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Progressor",
      "category": "Passing",
      "attribute": "Vision",
      "base_stat": 68,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Progressor",
      "category": "Passing",
      "attribute": "Centros",
      "base_stat": 58,
      "cap_stat": 78,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Progressor",
      "category": "Passing",
      "attribute": "Precision Faltas",
      "base_stat": 56,
      "cap_stat": 76,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Progressor",
      "category": "Passing",
      "attribute": "Pase Corto",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Progressor",
      "category": "Passing",
      "attribute": "Pase Largo",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Progressor",
      "category": "Passing",
      "attribute": "Efecto",
      "base_stat": 60,
      "cap_stat": 80,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Progressor",
      "category": "Ball Control",
      "attribute": "Agilidad",
      "base_stat": 64,
      "cap_stat": 84,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Progressor",
      "category": "Ball Control",
      "attribute": "Balance",
      "base_stat": 66,
      "cap_stat": 86,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Progressor",
      "category": "Ball Control",
      "attribute": "Reacciones",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Progressor",
      "category": "Ball Control",
      "attribute": "Control Balon",
      "base_stat": 74,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Progressor",
      "category": "Ball Control",
      "attribute": "Regates",
      "base_stat": 66,
      "cap_stat": 85,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Progressor",
      "category": "Ball Control",
      "attribute": "Compostura",
      "base_stat": 80,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Progressor",
      "category": "Defending",
      "attribute": "Intercepciones",
      "base_stat": 82,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Progressor",
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Progressor",
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "base_stat": 82,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Progressor",
      "category": "Defending",
      "attribute": "Robos",
      "base_stat": 82,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Progressor",
      "category": "Defending",
      "attribute": "Barridas",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Progressor",
      "category": "Physical",
      "attribute": "Salto",
      "base_stat": 74,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Progressor",
      "category": "Physical",
      "attribute": "Resistencia",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Progressor",
      "category": "Physical",
      "attribute": "Fuerza",
      "base_stat": 76,
      "cap_stat": 95,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Progressor",
      "category": "Physical",
      "attribute": "Agresividad",
      "base_stat": 76,
      "cap_stat": 95,
      "cost_tier": "Cheap"
    }
  ],
  "Marauder": [
    {
      "archetype": "Marauder",
      "category": "Pace",
      "attribute": "Aceleracion",
      "base_stat": 80,
      "cap_stat": 96,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Marauder",
      "category": "Pace",
      "attribute": "Sprint",
      "base_stat": 82,
      "cap_stat": 97,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Marauder",
      "category": "Scoring",
      "attribute": "Posicionamiento",
      "base_stat": 62,
      "cap_stat": 80,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Marauder",
      "category": "Scoring",
      "attribute": "Definicion",
      "base_stat": 55,
      "cap_stat": 75,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Marauder",
      "category": "Scoring",
      "attribute": "Potencia Tiro",
      "base_stat": 68,
      "cap_stat": 86,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Marauder",
      "category": "Scoring",
      "attribute": "Tiros Lejanos",
      "base_stat": 60,
      "cap_stat": 80,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Marauder",
      "category": "Scoring",
      "attribute": "Voleas",
      "base_stat": 56,
      "cap_stat": 75,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Marauder",
      "category": "Scoring",
      "attribute": "Penales",
      "base_stat": 58,
      "cap_stat": 76,
      "cost_tier": "Most Expensive"
    },
    {
      "archetype": "Marauder",
      "category": "Passing",
      "attribute": "Vision",
      "base_stat": 70,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Marauder",
      "category": "Passing",
      "attribute": "Centros",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Marauder",
      "category": "Passing",
      "attribute": "Precision Faltas",
      "base_stat": 60,
      "cap_stat": 80,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Marauder",
      "category": "Passing",
      "attribute": "Pase Corto",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Marauder",
      "category": "Passing",
      "attribute": "Pase Largo",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Marauder",
      "category": "Passing",
      "attribute": "Efecto",
      "base_stat": 70,
      "cap_stat": 88,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Marauder",
      "category": "Ball Control",
      "attribute": "Agilidad",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Marauder",
      "category": "Ball Control",
      "attribute": "Balance",
      "base_stat": 74,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Marauder",
      "category": "Ball Control",
      "attribute": "Reacciones",
      "base_stat": 76,
      "cap_stat": 95,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Marauder",
      "category": "Ball Control",
      "attribute": "Control Balon",
      "base_stat": 76,
      "cap_stat": 94,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Marauder",
      "category": "Ball Control",
      "attribute": "Regates",
      "base_stat": 74,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Marauder",
      "category": "Ball Control",
      "attribute": "Compostura",
      "base_stat": 74,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Marauder",
      "category": "Defending",
      "attribute": "Intercepciones",
      "base_stat": 76,
      "cap_stat": 95,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Marauder",
      "category": "Defending",
      "attribute": "Precision Cabeza",
      "base_stat": 68,
      "cap_stat": 86,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Marauder",
      "category": "Defending",
      "attribute": "Percepcion Defensiva",
      "base_stat": 76,
      "cap_stat": 95,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Marauder",
      "category": "Defending",
      "attribute": "Robos",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Marauder",
      "category": "Defending",
      "attribute": "Barridas",
      "base_stat": 80,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Marauder",
      "category": "Physical",
      "attribute": "Salto",
      "base_stat": 72,
      "cap_stat": 90,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Marauder",
      "category": "Physical",
      "attribute": "Resistencia",
      "base_stat": 84,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Marauder",
      "category": "Physical",
      "attribute": "Fuerza",
      "base_stat": 72,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Marauder",
      "category": "Physical",
      "attribute": "Agresividad",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    }
  ],
  "Shot Stopper": [
    {
      "archetype": "Shot Stopper",
      "category": "Goalkeeping",
      "attribute": "GK_Estirada",
      "base_stat": 78,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Shot Stopper",
      "category": "Goalkeeping",
      "attribute": "GK_Paradas",
      "base_stat": 76,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Shot Stopper",
      "category": "Goalkeeping",
      "attribute": "GK_Saque",
      "base_stat": 68,
      "cap_stat": 88,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Shot Stopper",
      "category": "Goalkeeping",
      "attribute": "GK_Reflejos",
      "base_stat": 82,
      "cap_stat": 99,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Shot Stopper",
      "category": "Goalkeeping",
      "attribute": "GK_Colocacion",
      "base_stat": 78,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Shot Stopper",
      "category": "Physical",
      "attribute": "Reacciones",
      "base_stat": 78,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Shot Stopper",
      "category": "Physical",
      "attribute": "Salto",
      "base_stat": 75,
      "cap_stat": 95,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Shot Stopper",
      "category": "Physical",
      "attribute": "Resistencia",
      "base_stat": 65,
      "cap_stat": 85,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Shot Stopper",
      "category": "Physical",
      "attribute": "Fuerza",
      "base_stat": 70,
      "cap_stat": 90,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Shot Stopper",
      "category": "Physical",
      "attribute": "Sprint",
      "base_stat": 60,
      "cap_stat": 80,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Shot Stopper",
      "category": "Physical",
      "attribute": "Aceleracion",
      "base_stat": 60,
      "cap_stat": 80,
      "cost_tier": "Expensive"
    }
  ],
  "Sweeper Keeper": [
    {
      "archetype": "Sweeper Keeper",
      "category": "Goalkeeping",
      "attribute": "GK_Estirada",
      "base_stat": 76,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Sweeper Keeper",
      "category": "Goalkeeping",
      "attribute": "GK_Paradas",
      "base_stat": 74,
      "cap_stat": 94,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Sweeper Keeper",
      "category": "Goalkeeping",
      "attribute": "GK_Saque",
      "base_stat": 78,
      "cap_stat": 98,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Sweeper Keeper",
      "category": "Goalkeeping",
      "attribute": "GK_Reflejos",
      "base_stat": 78,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Sweeper Keeper",
      "category": "Goalkeeping",
      "attribute": "GK_Colocacion",
      "base_stat": 76,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Sweeper Keeper",
      "category": "Physical",
      "attribute": "Reacciones",
      "base_stat": 76,
      "cap_stat": 96,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Sweeper Keeper",
      "category": "Passing",
      "attribute": "Pase Corto",
      "base_stat": 72,
      "cap_stat": 92,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Sweeper Keeper",
      "category": "Passing",
      "attribute": "Pase Largo",
      "base_stat": 75,
      "cap_stat": 95,
      "cost_tier": "Cheapest"
    },
    {
      "archetype": "Sweeper Keeper",
      "category": "Physical",
      "attribute": "Salto",
      "base_stat": 72,
      "cap_stat": 92,
      "cost_tier": "Cheap"
    },
    {
      "archetype": "Sweeper Keeper",
      "category": "Physical",
      "attribute": "Resistencia",
      "base_stat": 68,
      "cap_stat": 88,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Sweeper Keeper",
      "category": "Physical",
      "attribute": "Aceleracion",
      "base_stat": 65,
      "cap_stat": 85,
      "cost_tier": "Expensive"
    },
    {
      "archetype": "Sweeper Keeper",
      "category": "Physical",
      "attribute": "Sprint",
      "base_stat": 65,
      "cap_stat": 85,
      "cost_tier": "Expensive"
    }
  ]
};

export function getArchetypeAttributes(name: string): ArchetypeAttribute[] {
  return ATTRIBUTES_BY_ARCHETYPE[name] ?? [];
}

/** All attribute names referenced by any archetype (stable order). */
export const ALL_ATTRIBUTES: string[] = Array.from(
  new Set(Object.values(ATTRIBUTES_BY_ARCHETYPE).flat().map((a) => a.attribute)),
);

export const CATEGORIES_BY_ARCHETYPE: Record<string, string[]> = Object.fromEntries(
  Object.entries(ATTRIBUTES_BY_ARCHETYPE).map(([name, attrs]) => [
    name,
    Array.from(new Set(attrs.map((a) => a.category))),
  ]),
);
