// AUTO-GENERATED by scripts/generate-data.mjs from raw-data/. Do not edit by hand.
import type { ArchetypeStars } from "@/types";

export const ARCHETYPE_STARS: ArchetypeStars[] = [
  {
    "archetype": "Shot Stopper",
    "base_skills": 1,
    "max_skills": 2,
    "cost_skills_3": 0,
    "cost_skills_4": 0,
    "cost_skills_5": 0,
    "base_weak_foot": 1,
    "max_weak_foot": 3,
    "cost_wf_3": 20,
    "cost_wf_4": 0,
    "cost_wf_5": 0
  },
  {
    "archetype": "Sweeper Keeper",
    "base_skills": 1,
    "max_skills": 3,
    "cost_skills_3": 10,
    "cost_skills_4": 0,
    "cost_skills_5": 0,
    "base_weak_foot": 1,
    "max_weak_foot": 4,
    "cost_wf_3": 15,
    "cost_wf_4": 25,
    "cost_wf_5": 0
  },
  {
    "archetype": "Progressor",
    "base_skills": 2,
    "max_skills": 4,
    "cost_skills_3": 10,
    "cost_skills_4": 20,
    "cost_skills_5": 0,
    "base_weak_foot": 3,
    "max_weak_foot": 4,
    "cost_wf_3": 0,
    "cost_wf_4": 25,
    "cost_wf_5": 0
  },
  {
    "archetype": "Boss",
    "base_skills": 2,
    "max_skills": 3,
    "cost_skills_3": 10,
    "cost_skills_4": 0,
    "cost_skills_5": 0,
    "base_weak_foot": 2,
    "max_weak_foot": 4,
    "cost_wf_3": 20,
    "cost_wf_4": 35,
    "cost_wf_5": 0
  },
  {
    "archetype": "Disruptor",
    "base_skills": 2,
    "max_skills": 4,
    "cost_skills_3": 10,
    "cost_skills_4": 20,
    "cost_skills_5": 0,
    "base_weak_foot": 3,
    "max_weak_foot": 5,
    "cost_wf_3": 0,
    "cost_wf_4": 35,
    "cost_wf_5": 50
  },
  {
    "archetype": "Marauder",
    "base_skills": 2,
    "max_skills": 5,
    "cost_skills_3": 10,
    "cost_skills_4": 20,
    "cost_skills_5": 35,
    "base_weak_foot": 3,
    "max_weak_foot": 5,
    "cost_wf_3": 0,
    "cost_wf_4": 25,
    "cost_wf_5": 40
  },
  {
    "archetype": "Recycler",
    "base_skills": 2,
    "max_skills": 4,
    "cost_skills_3": 8,
    "cost_skills_4": 15,
    "cost_skills_5": 0,
    "base_weak_foot": 3,
    "max_weak_foot": 5,
    "cost_wf_3": 0,
    "cost_wf_4": 25,
    "cost_wf_5": 40
  },
  {
    "archetype": "Maestro",
    "base_skills": 2,
    "max_skills": 5,
    "cost_skills_3": 10,
    "cost_skills_4": 20,
    "cost_skills_5": 35,
    "base_weak_foot": 3,
    "max_weak_foot": 5,
    "cost_wf_3": 0,
    "cost_wf_4": 25,
    "cost_wf_5": 40
  },
  {
    "archetype": "Creator",
    "base_skills": 2,
    "max_skills": 5,
    "cost_skills_3": 10,
    "cost_skills_4": 20,
    "cost_skills_5": 35,
    "base_weak_foot": 3,
    "max_weak_foot": 5,
    "cost_wf_3": 0,
    "cost_wf_4": 25,
    "cost_wf_5": 40
  },
  {
    "archetype": "Spark",
    "base_skills": 3,
    "max_skills": 5,
    "cost_skills_3": 0,
    "cost_skills_4": 15,
    "cost_skills_5": 25,
    "base_weak_foot": 3,
    "max_weak_foot": 5,
    "cost_wf_3": 0,
    "cost_wf_4": 25,
    "cost_wf_5": 40
  },
  {
    "archetype": "Magician",
    "base_skills": 3,
    "max_skills": 5,
    "cost_skills_3": 0,
    "cost_skills_4": 20,
    "cost_skills_5": 35,
    "base_weak_foot": 3,
    "max_weak_foot": 5,
    "cost_wf_3": 0,
    "cost_wf_4": 25,
    "cost_wf_5": 40
  },
  {
    "archetype": "Finisher",
    "base_skills": 3,
    "max_skills": 5,
    "cost_skills_3": 0,
    "cost_skills_4": 15,
    "cost_skills_5": 25,
    "base_weak_foot": 3,
    "max_weak_foot": 5,
    "cost_wf_3": 0,
    "cost_wf_4": 35,
    "cost_wf_5": 50
  },
  {
    "archetype": "Target",
    "base_skills": 2,
    "max_skills": 5,
    "cost_skills_3": 8,
    "cost_skills_4": 15,
    "cost_skills_5": 25,
    "base_weak_foot": 2,
    "max_weak_foot": 5,
    "cost_wf_3": 20,
    "cost_wf_4": 35,
    "cost_wf_5": 50
  }
];

export const STARS_BY_ARCHETYPE: Record<string, ArchetypeStars> =
  Object.fromEntries(ARCHETYPE_STARS.map((s) => [s.archetype, s]));

export function getStars(name: string): ArchetypeStars | undefined {
  return STARS_BY_ARCHETYPE[name];
}
