// AUTO-GENERATED by scripts/generate-data.mjs from raw-data/. Do not edit by hand.
import type { CostTierRange } from "@/types";

export const COST_TIERS_TABLE: CostTierRange[] = [
  {
    "min": 1,
    "max": 60,
    "rates": {
      "Cheapest": 1,
      "Cheap": 1,
      "Expensive": 1,
      "Most Expensive": 2
    }
  },
  {
    "min": 61,
    "max": 63,
    "rates": {
      "Cheapest": 1,
      "Cheap": 1,
      "Expensive": 2,
      "Most Expensive": 3
    }
  },
  {
    "min": 64,
    "max": 66,
    "rates": {
      "Cheapest": 1,
      "Cheap": 2,
      "Expensive": 3,
      "Most Expensive": 4
    }
  },
  {
    "min": 67,
    "max": 69,
    "rates": {
      "Cheapest": 1,
      "Cheap": 2,
      "Expensive": 3,
      "Most Expensive": 5
    }
  },
  {
    "min": 70,
    "max": 74,
    "rates": {
      "Cheapest": 2,
      "Cheap": 3,
      "Expensive": 4,
      "Most Expensive": 6
    }
  },
  {
    "min": 75,
    "max": 79,
    "rates": {
      "Cheapest": 3,
      "Cheap": 4,
      "Expensive": 6,
      "Most Expensive": 8
    }
  },
  {
    "min": 80,
    "max": 84,
    "rates": {
      "Cheapest": 3,
      "Cheap": 5,
      "Expensive": 7,
      "Most Expensive": 10
    }
  },
  {
    "min": 85,
    "max": 89,
    "rates": {
      "Cheapest": 6,
      "Cheap": 8,
      "Expensive": 11,
      "Most Expensive": 15
    }
  },
  {
    "min": 90,
    "max": 92,
    "rates": {
      "Cheapest": 8,
      "Cheap": 11,
      "Expensive": 15,
      "Most Expensive": 20
    }
  },
  {
    "min": 93,
    "max": 94,
    "rates": {
      "Cheapest": 10,
      "Cheap": 15,
      "Expensive": 20,
      "Most Expensive": 25
    }
  },
  {
    "min": 95,
    "max": 95,
    "rates": {
      "Cheapest": 15,
      "Cheap": 20,
      "Expensive": 25,
      "Most Expensive": 30
    }
  },
  {
    "min": 96,
    "max": 96,
    "rates": {
      "Cheapest": 20,
      "Cheap": 25,
      "Expensive": 30,
      "Most Expensive": 35
    }
  },
  {
    "min": 97,
    "max": 97,
    "rates": {
      "Cheapest": 25,
      "Cheap": 30,
      "Expensive": 35,
      "Most Expensive": 40
    }
  },
  {
    "min": 98,
    "max": 98,
    "rates": {
      "Cheapest": 30,
      "Cheap": 35,
      "Expensive": 40,
      "Most Expensive": 45
    }
  },
  {
    "min": 99,
    "max": 99,
    "rates": {
      "Cheapest": 35,
      "Cheap": 40,
      "Expensive": 45,
      "Most Expensive": 50
    }
  }
];
